site_name: Seumoo Docs
site_url: https://seumoo.com/seumoo-docs
repo_url: https://github.com/seumoo/seumoo-docs
site_dir: seumoo-docs
theme:
    name: material
    custom_dir: overrides
    logo: img/logo_black.svg
    favicon: img/favicon.ico
    palette:
        primary: seumoo-docs
        accent: amber
    features:
        - navigation.tabs
        - content.tabs.link
        - navigation.top
markdown_extensions:
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
            custom_icons:
                - overrides/.icons
copyright: Copyright &copy; 2022 Seumoo
extra_css:
    - css/extra.css
nav:
    - Home: index.md
    - Documentation Samples: 
        - Quick Start Guide to Exploring Fruit City Crashes: quick-start.md    
        # - Another Test: whale-tutorial.md  